<?php declare( strict_types = 1 );

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class BypassForceLogin {
	private $bypass_force_login_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'bypass_force_login_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'bypass_force_login_page_init' ) );
	}

	public function bypass_force_login_add_plugin_page() {
		add_options_page(
			'Bypass Force Login', // page_title
			'Bypass Force Login', // menu_title
			'manage_options', // capability
			'bypass-force-login', // menu_slug
			array( $this, 'bypass_force_login_create_admin_page' ) // function
		);
	}

	public function bypass_force_login_create_admin_page() {
		$this->bypass_force_login_options = get_option( 'bypass_force_login_option_name' ); ?>

		<div class="wrap">
			<h2>Bypass Force Login</h2>
			<p>lorem</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'bypass_force_login_option_group' );
					do_settings_sections( 'bypass-force-login-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function bypass_force_login_page_init() {
		register_setting(
			'bypass_force_login_option_group', // option_group
			'bypass_force_login_option_name', // option_name
			array( $this, 'bypass_force_login_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'bypass_force_login_setting_section', // id
			'Settings', // title
			array( $this, 'bypass_force_login_section_info' ), // callback
			'bypass-force-login-admin' // page
		);

		add_settings_field(
			'add_url_0', // id
			'Add URL', // title
			array( $this, 'add_url_0_callback' ), // callback
			'bypass-force-login-admin', // page
			'bypass_force_login_setting_section' // section
		);

		add_settings_field(
			'page_1', // id
			'Page', // title
			array( $this, 'page_1_callback' ), // callback
			'bypass-force-login-admin', // page
			'bypass_force_login_setting_section' // section
		);
	}

	public function bypass_force_login_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['add_url_0'] ) ) {
			$sanitary_values['add_url_0'] = esc_textarea( $input['add_url_0'] );
		}

		if ( isset( $input['page_1'] ) ) {
			$sanitary_values['page_1'] = $input['page_1'];
		}

		return $sanitary_values;
	}

	public function bypass_force_login_section_info() {

	}

	public function add_url_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="bypass_force_login_option_name[add_url_0]" id="add_url_0">%s</textarea>',
			isset( $this->bypass_force_login_options['add_url_0'] ) ? esc_attr( $this->bypass_force_login_options['add_url_0']) : ''
		);
	}

	public function page_1_callback() {
		?> <select name="bypass_force_login_option_name[page_1]" id="page_1">
			<?php $selected = (isset( $this->bypass_force_login_options['page_1'] ) && $this->bypass_force_login_options['page_1'] === 'option-one') ? 'selected' : '' ; ?>
			<option value="option-one" <?php echo $selected; ?>>Option One</option>
		</select> <?php
	}

}
if ( is_admin() )
	$bypass_force_login = new BypassForceLogin();

/*
 * Retrieve this value with:
 * $bypass_force_login_options = get_option( 'bypass_force_login_option_name' ); // Array of All Options
 * $add_url_0 = $bypass_force_login_options['add_url_0']; // Add URL
 * $page_1 = $bypass_force_login_options['page_1']; // Page
 */
